run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - bodyclose
    - errorlint
    - gofmt
    - goimports
    - revive
    - gocritic
    - gosec
    - goconst
    - unparam
    - nilerr
    - makezero
    - nakedret
    - copyloopvar

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - experimental
      - opinionated

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
