package httpadapter

import (
	"time"

	"github.com/galenos-pro/appointments-api/internal/domain"
	"github.com/galenos-pro/appointments-api/internal/ports/shared"
)

// createAppointmentRequest es el contrato de entrada esperado desde Angular.
type createAppointmentRequest struct {
	PatientID string    `json:"patientId" binding:"required"`
	DoctorID  string    `json:"doctorId" binding:"required"`
	StartsAt  time.Time `json:"startsAt" binding:"required"`
	EndsAt    time.Time `json:"endsAt" binding:"required"`
	Reason    string    `json:"reason" binding:"required,max=500"`
}

// pageResponsePatients describe la respuesta paginada de pacientes para Swagger.
type pageResponsePatients = shared.PageResponse[domain.Patient]

// updatePatientRequest es el cuerpo de PUT /api/v1/pacientes/:id. Repite los
// campos editables de domain.PatientUpdate para que el binding de Gin sea
// explícito en el adaptador HTTP.
type updatePatientRequest struct {
	BirthCountryID    *int64     `json:"birthCountryId"`
	MaternalSurname   *string    `json:"maternalSurname"`
	HomeAddress       *string    `json:"homeAddress"`
	OriginCountryID   *int64     `json:"originCountryId"`
	PaternalSurname   *string    `json:"paternalSurname"`
	FirstName         *string    `json:"firstName"`
	SecondName        *string    `json:"secondName"`
	ThirdName         *string    `json:"thirdName"`
	DateOfBirth       *time.Time `json:"dateOfBirth"`
	DocumentNumber    *string    `json:"documentNumber"`
	Phone             *string    `json:"phone"`
	Cellphone         *string    `json:"cellphone"`
	AutoGenerated     *string    `json:"autoGenerated"`
	SexTypeID         *int64     `json:"sexTypeId"`
	OriginID          *int64     `json:"originId"`
	EducationDegreeID *int64     `json:"educationDegreeId"`
	MaritalStatusID   *int64     `json:"maritalStatusId"`
	DocIdentityID     *int64     `json:"docIdentityId"`
	OccupationTypeID  *int64     `json:"occupationTypeId"`
	HomeCenterID      *int64     `json:"homeCenterId"`
	FatherName        *string    `json:"fatherName"`
	MotherName        *string    `json:"motherName"`
	HomeCountryID     *int64     `json:"homeCountryId"`
	HistoryNumber     *int64     `json:"historyNumber"`
	BirthCenterID     *int64     `json:"birthCenterId"`
	OriginCenterID    *int64     `json:"originCenterId"`
	OriginDistrictID  *int64     `json:"originDistrictId"`
	HomeDistrictID    *int64     `json:"homeDistrictId"`
	BirthDistrictID   *int64     `json:"birthDistrictId"`
	EthnicityID       *string    `json:"ethnicityId"`
	LanguageID        *int64     `json:"languageId"`
	Email             *string    `json:"email"`
	DisabilityID      *int64     `json:"disabilityId"`
	IncapacityID      *int64     `json:"incapacityId"`
	AuditUserID       *int64     `json:"auditUserId"`
}

// createTriajeRequest es el cuerpo de POST /api/v1/triaje. Cada campo es
// puntero para que el frontend pueda enviar solo los datos que recopiló;
// los que faltan se persisten como NULL en el SP.
type createTriajeRequest struct {
	IDTriaje                  *int64     `json:"idTriaje"`
	DocIdentityType           *int64     `json:"idDocIdentidad"`
	DocumentNumber            *string    `json:"nroDocumento"`
	PaternalSurname           *string    `json:"apellidoPaterno"`
	MaternalSurname           *string    `json:"apellidoMaterno"`
	FirstName                 *string    `json:"primerNombre"`
	SecondName                *string    `json:"segundoNombre"`
	ThirdName                 *string    `json:"tercerNombre"`
	SexTypeID                 *int64     `json:"idSexo"`
	DateOfBirth               *time.Time `json:"fechaNacimiento"`
	Phone                     *string    `json:"telefono"`
	HomeDepartmentID          *int64     `json:"idDepartamentoDomicilio"`
	HomeProvinceID            *int64     `json:"idProvinciaDomicilio"`
	HomeDistrictID            *int64     `json:"idDistritoDomicilio"`
	HomeCommunityID           *int64     `json:"idComunidadDomicilio"`
	HomeAddress               *string    `json:"direccion"`
	IsTrafficAccident         *int64     `json:"idEsAccidenteTransito"`
	FundingSourceID           *int64     `json:"idFuenteFinanciamiento"`
	Email                     *string    `json:"email"`
	MaritalStatusID           *int64     `json:"idEstadoCivil"`
	HeartRate                 *int64     `json:"frecCardiaca"`
	Temperature               *float64   `json:"temperatura"`
	BloodPressure             *string    `json:"presionArterial"`
	Oxygen                    *int64     `json:"saturacion"`
	RespiratoryRate           *int64     `json:"frecRespiratoria"`
	FiO2                      *int64     `json:"fiO2"`
	Weight                    *float64   `json:"peso"`
	Height                    *float64   `json:"talla"`
	BMI                       *float64   `json:"imc"`
	EvolutionTimeQuantity     *int64     `json:"tiempoEvolucionCantidad"`
	EvolutionTimeQuantityUnit *string    `json:"tiempoEvolucionCantidadUnidad"`
	PainScale                 *int64     `json:"escalaDolor"`
	GlasgowScale              *int64     `json:"escalaGlasgow"`
	PriorityTypeID            *int64     `json:"idTipoPrioridad"`
	ServiceID                 *int64     `json:"idServicio"`
	Motivo                    *string    `json:"motivo"`
	IsPregnant                *int64     `json:"gestante"`
	ArrivalStateID            *int64     `json:"idEstadollego"`
	Photo                     *string    `json:"foto"`
	EmployeeID                *int64     `json:"idEmpleado"`
}

// toDomain mapea el request HTTP al objeto de dominio para el SP.
func (r createTriajeRequest) toDomain() *domain.Triage {
	return &domain.Triage{
		IDTriaje:                  r.IDTriaje,
		DocIdentityID:             r.DocIdentityType,
		DocumentNumber:            r.DocumentNumber,
		PaternalSurname:           r.PaternalSurname,
		MaternalSurname:           r.MaternalSurname,
		FirstName:                 r.FirstName,
		SecondName:                r.SecondName,
		ThirdName:                 r.ThirdName,
		SexTypeID:                 r.SexTypeID,
		DateOfBirth:               r.DateOfBirth,
		Phone:                     r.Phone,
		HomeDepartmentID:          r.HomeDepartmentID,
		HomeProvinceID:            r.HomeProvinceID,
		HomeDistrictID:            r.HomeDistrictID,
		HomeCommunityID:           r.HomeCommunityID,
		HomeAddress:               r.HomeAddress,
		IsTrafficAccident:         r.IsTrafficAccident,
		FundingSourceID:           r.FundingSourceID,
		Email:                     r.Email,
		MaritalStatusID:           r.MaritalStatusID,
		HeartRate:                 r.HeartRate,
		Temperature:               r.Temperature,
		BloodPressure:             r.BloodPressure,
		OxygenSaturation:          r.Oxygen,
		RespiratoryRate:           r.RespiratoryRate,
		FiO2:                      r.FiO2,
		Weight:                    r.Weight,
		Height:                    r.Height,
		BMI:                       r.BMI,
		EvolutionTimeQuantity:     r.EvolutionTimeQuantity,
		EvolutionTimeQuantityUnit: r.EvolutionTimeQuantityUnit,
		PainScale:                 r.PainScale,
		GlasgowScale:              r.GlasgowScale,
		PriorityTypeID:            r.PriorityTypeID,
		ServiceID:                 r.ServiceID,
		Motivo:                    r.Motivo,
		IsPregnant:                r.IsPregnant,
		ArrivalStateID:            r.ArrivalStateID,
		Photo:                     r.Photo,
		EmployeeID:                r.EmployeeID,
	}
}

// createAdmissionFromTriageRequest es el cuerpo de POST
// /api/v1/triaje/admision. Los campos opcionales son punteros para que el
// frontend envíe solo los que tiene; los que falten se persisten como NULL.
type createAdmissionFromTriageRequest struct {
	IDTriaje            *int64  `json:"idTriaje" binding:"required"`
	IDPacienteTriaje    *int64  `json:"idPacienteTriaje" binding:"required"`
	IDEmpleado          *int64  `json:"idEmpleado"`
	NombreAcompanante   *string `json:"nombreAcompanante"`
	TelefonoAcompanante *string `json:"telefonoAcompanante"`
	DireccionPaciente   *string `json:"direccionPaciente"`
	Observacion         *string `json:"observacion"`
}

// toDomain mapea el request HTTP al objeto de dominio para el SP.
func (r createAdmissionFromTriageRequest) toDomain() *domain.AdmisionDesdeTriaje {
	return &domain.AdmisionDesdeTriaje{
		IDTriaje:            r.IDTriaje,
		IDPacienteTriaje:    r.IDPacienteTriaje,
		IDEmpleado:          r.IDEmpleado,
		NombreAcompanante:   r.NombreAcompanante,
		TelefonoAcompanante: r.TelefonoAcompanante,
		DireccionPaciente:   r.DireccionPaciente,
		Observacion:         r.Observacion,
	}
}

// toDomain mapea el request HTTP al objeto de dominio.
func (r updatePatientRequest) toDomain() domain.PatientUpdate {
	return domain.PatientUpdate{
		BirthCountryID:    r.BirthCountryID,
		MaternalSurname:   r.MaternalSurname,
		HomeAddress:       r.HomeAddress,
		OriginCountryID:   r.OriginCountryID,
		PaternalSurname:   r.PaternalSurname,
		FirstName:         r.FirstName,
		SecondName:        r.SecondName,
		ThirdName:         r.ThirdName,
		DateOfBirth:       r.DateOfBirth,
		DocumentNumber:    r.DocumentNumber,
		Phone:             r.Phone,
		Cellphone:         r.Cellphone,
		AutoGenerated:     r.AutoGenerated,
		SexTypeID:         r.SexTypeID,
		OriginID:          r.OriginID,
		EducationDegreeID: r.EducationDegreeID,
		MaritalStatusID:   r.MaritalStatusID,
		DocIdentityID:     r.DocIdentityID,
		OccupationTypeID:  r.OccupationTypeID,
		HomeCenterID:      r.HomeCenterID,
		FatherName:        r.FatherName,
		MotherName:        r.MotherName,
		HomeCountryID:     r.HomeCountryID,
		HistoryNumber:     r.HistoryNumber,
		BirthCenterID:     r.BirthCenterID,
		OriginCenterID:    r.OriginCenterID,
		OriginDistrictID:  r.OriginDistrictID,
		HomeDistrictID:    r.HomeDistrictID,
		BirthDistrictID:   r.BirthDistrictID,
		EthnicityID:       r.EthnicityID,
		LanguageID:        r.LanguageID,
		Email:             r.Email,
		DisabilityID:      r.DisabilityID,
		IncapacityID:      r.IncapacityID,
		AuditUserID:       r.AuditUserID,
	}
}
