package httpadapter

import (
	"time"

	"github.com/galenos-pro/appointments-api/internal/domain"
)

// --- PATIENT RESPONSES ---

type patientResponse struct {
	PatientID         int64      `json:"patientId"`
	DocumentNumber    string     `json:"documentNumber"`
	HistoryNumber     string     `json:"historyNumber"`
	PaternalSurname   string     `json:"paternalSurname"`
	MaternalSurname   string     `json:"maternalSurname"`
	FirstName         string     `json:"firstName"`
	SecondName        string     `json:"secondName"`
	ThirdName         string     `json:"thirdName"`
	DateOfBirth       *time.Time `json:"dateOfBirth,omitempty"`
	HomeDistrictID    *int64     `json:"homeDistrictId,omitempty"`
	HomeCenterID      *int64     `json:"homeCenterId,omitempty"`
	SexTypeID         *int64     `json:"sexTypeId,omitempty"`
	MaritalStatusID   *int64     `json:"maritalStatusId,omitempty"`
	EducationDegreeID *int64     `json:"educationDegreeId,omitempty"`
	HomeAddress       *string    `json:"homeAddress,omitempty"`
	Phone             *string    `json:"phone,omitempty"`
}

func toPatientResponse(p domain.Patient) patientResponse {
	return patientResponse{
		PatientID:         p.PatientID,
		DocumentNumber:    p.DocumentNumber,
		HistoryNumber:     p.HistoryNumber,
		PaternalSurname:   p.PaternalSurname,
		MaternalSurname:   p.MaternalSurname,
		FirstName:         p.FirstName,
		SecondName:        p.SecondName,
		ThirdName:         p.ThirdName,
		DateOfBirth:       p.DateOfBirth,
		HomeDistrictID:    p.HomeDistrictID,
		HomeCenterID:      p.HomeCenterID,
		SexTypeID:         p.SexTypeID,
		MaritalStatusID:   p.MaritalStatusID,
		EducationDegreeID: p.EducationDegreeID,
		HomeAddress:       p.HomeAddress,
		Phone:             p.Phone,
	}
}

type patientDetailResponse struct {
	PatientID             int64      `json:"patientId"`
	DocumentNumber        *string    `json:"documentNumber,omitempty"`
	HistoryNumber         *string    `json:"historyNumber,omitempty"`
	PaternalSurname       *string    `json:"paternalSurname,omitempty"`
	MaternalSurname       *string    `json:"maternalSurname,omitempty"`
	FirstName             *string    `json:"firstName,omitempty"`
	SecondName            *string    `json:"secondName,omitempty"`
	ThirdName             *string    `json:"thirdName,omitempty"`
	DateOfBirth           *time.Time `json:"dateOfBirth,omitempty"`
	Phone                 *string    `json:"phone,omitempty"`
	HomeAddress           *string    `json:"homeAddress,omitempty"`
	AutoGenerated         *string    `json:"autoGenerated,omitempty"`
	SexTypeID             *int64     `json:"sexTypeId,omitempty"`
	OriginID              *int64     `json:"originId,omitempty"`
	EducationDegreeID     *int64     `json:"educationDegreeId,omitempty"`
	MaritalStatusID       *int64     `json:"maritalStatusId,omitempty"`
	DocIdentityID         *int64     `json:"docIdentityId,omitempty"`
	OccupationTypeID      *int64     `json:"occupationTypeId,omitempty"`
	BirthCenterID         *int64     `json:"birthCenterId,omitempty"`
	HomeCenterID          *int64     `json:"homeCenterId,omitempty"`
	FatherName            *string    `json:"fatherName,omitempty"`
	MotherName            *string    `json:"motherName,omitempty"`
	NumberingTypeID       *int64     `json:"numberingTypeId,omitempty"`
	OriginCenterID        *int64     `json:"originCenterId,omitempty"`
	Observation           *string    `json:"observation,omitempty"`
	HomeCountryID         *int64     `json:"homeCountryId,omitempty"`
	OriginCountryID       *int64     `json:"originCountryId,omitempty"`
	BirthCountryID        *int64     `json:"birthCountryId,omitempty"`
	OriginDistrictID      *int64     `json:"originDistrictId,omitempty"`
	HomeDistrictID        *int64     `json:"homeDistrictId,omitempty"`
	BirthDistrictID       *int64     `json:"birthDistrictId,omitempty"`
	FamilyRecord          *string    `json:"familyRecord,omitempty"`
	EthnicityID           *string    `json:"ethnicityId,omitempty"`
	BloodType             *string    `json:"bloodType,omitempty"`
	RhFactor              *string    `json:"rhFactor,omitempty"`
	UsesWebReniec         *bool      `json:"usesWebReniec,omitempty"`
	LanguageID            *int64     `json:"languageId,omitempty"`
	Email                 *string    `json:"email,omitempty"`
	MotherDocument        *string    `json:"motherDocument,omitempty"`
	MotherPaternalSurname *string    `json:"motherPaternalSurname,omitempty"`
	MotherMaternalSurname *string    `json:"motherMaternalSurname,omitempty"`
	MotherFirstName       *string    `json:"motherFirstName,omitempty"`
	MotherSecondName      *string    `json:"motherSecondName,omitempty"`
	ChildOrderNumber      *int64     `json:"childOrderNumber,omitempty"`
	MotherDocType         *string    `json:"motherDocType,omitempty"`
	Sector                *string    `json:"sector,omitempty"`
	Sectorist             *string    `json:"sectorist,omitempty"`
	BirthRecordNumber     *string    `json:"birthRecordNumber,omitempty"`
	EcoGenCaseNumber      *string    `json:"ecoGenCaseNumber,omitempty"`
	XRayCaseNumber        *string    `json:"xRayCaseNumber,omitempty"`
	EcogObsCaseNumber     *string    `json:"ecogObsCaseNumber,omitempty"`
	StateID               *int64     `json:"stateId,omitempty"`
	Cellphone             *string    `json:"cellphone,omitempty"`
	InsuranceTypeID       *int64     `json:"insuranceTypeId,omitempty"`
	PatientPhoto          *string    `json:"patientPhoto,omitempty"`
	PatientSignature      *string    `json:"patientSignature,omitempty"`
	DisabilityID          *int64     `json:"disabilityId,omitempty"`
	IncapacityID          *int64     `json:"incapacityId,omitempty"`
}

func toPatientDetailResponse(p domain.PatientDetail) patientDetailResponse {
	return patientDetailResponse{
		PatientID:             p.PatientID,
		DocumentNumber:        p.DocumentNumber,
		HistoryNumber:         p.HistoryNumber,
		PaternalSurname:       p.PaternalSurname,
		MaternalSurname:       p.MaternalSurname,
		FirstName:             p.FirstName,
		SecondName:            p.SecondName,
		ThirdName:             p.ThirdName,
		DateOfBirth:           p.DateOfBirth,
		Phone:                 p.Phone,
		HomeAddress:           p.HomeAddress,
		AutoGenerated:         p.AutoGenerated,
		SexTypeID:             p.SexTypeID,
		OriginID:              p.OriginID,
		EducationDegreeID:     p.EducationDegreeID,
		MaritalStatusID:       p.MaritalStatusID,
		DocIdentityID:         p.DocIdentityID,
		OccupationTypeID:      p.OccupationTypeID,
		BirthCenterID:         p.BirthCenterID,
		HomeCenterID:          p.HomeCenterID,
		FatherName:            p.FatherName,
		MotherName:            p.MotherName,
		NumberingTypeID:       p.NumberingTypeID,
		OriginCenterID:        p.OriginCenterID,
		Observation:           p.Observation,
		HomeCountryID:         p.HomeCountryID,
		OriginCountryID:       p.OriginCountryID,
		BirthCountryID:        p.BirthCountryID,
		OriginDistrictID:      p.OriginDistrictID,
		HomeDistrictID:        p.HomeDistrictID,
		BirthDistrictID:       p.BirthDistrictID,
		FamilyRecord:          p.FamilyRecord,
		EthnicityID:           p.EthnicityID,
		BloodType:             p.BloodType,
		RhFactor:              p.RhFactor,
		UsesWebReniec:         p.UsesWebReniec,
		LanguageID:            p.LanguageID,
		Email:                 p.Email,
		MotherDocument:        p.MotherDocument,
		MotherPaternalSurname: p.MotherPaternalSurname,
		MotherMaternalSurname: p.MotherMaternalSurname,
		MotherFirstName:       p.MotherFirstName,
		MotherSecondName:      p.MotherSecondName,
		ChildOrderNumber:      p.ChildOrderNumber,
		MotherDocType:         p.MotherDocType,
		Sector:                p.Sector,
		Sectorist:             p.Sectorist,
		BirthRecordNumber:     p.BirthRecordNumber,
		EcoGenCaseNumber:      p.EcoGenCaseNumber,
		XRayCaseNumber:        p.XRayCaseNumber,
		EcogObsCaseNumber:     p.EcogObsCaseNumber,
		StateID:               p.StateID,
		Cellphone:             p.Cellphone,
		InsuranceTypeID:       p.InsuranceTypeID,
		PatientPhoto:          p.PatientPhoto,
		PatientSignature:      p.PatientSignature,
		DisabilityID:          p.DisabilityID,
		IncapacityID:          p.IncapacityID,
	}
}

// --- APPOINTMENT RESPONSES ---

type timeSlotResponse struct {
	StartsAt time.Time `json:"startsAt"`
	EndsAt   time.Time `json:"endsAt"`
}

type appointmentResponse struct {
	ID        string           `json:"id"`
	PatientID string           `json:"patientId"`
	DoctorID  string           `json:"doctorId"`
	Slot      timeSlotResponse `json:"slot"`
	Status    string           `json:"status"`
	Reason    string           `json:"reason"`
	CreatedAt time.Time        `json:"createdAt"`
	UpdatedAt time.Time        `json:"updatedAt"`
}

func toAppointmentResponse(a domain.Appointment) appointmentResponse {
	return appointmentResponse{
		ID:        string(a.ID),
		PatientID: string(a.PatientID),
		DoctorID:  string(a.DoctorID),
		Slot: timeSlotResponse{
			StartsAt: a.Slot.StartsAt,
			EndsAt:   a.Slot.EndsAt,
		},
		Status:    string(a.Status),
		Reason:    a.Reason,
		CreatedAt: a.CreatedAt,
		UpdatedAt: a.UpdatedAt,
	}
}

// --- EXTERNAL RESPONSES ---

type reniecDatosResponse struct {
	ApellidoPaterno string `json:"apellidoPaterno"`
	ApellidoMaterno string `json:"apellidoMaterno"`
	Nombres         string `json:"nombres"`
	PrimerNombre    string `json:"primerNombre"`
	SegundoNombre   string `json:"segundoNombre"`
	TercerNombre    string `json:"tercerNombre"`
	FechaNacimiento string `json:"fechaNacimiento"`
	Sexo            string `json:"sexo"`
}

type reniecResultResponse struct {
	DNI       string              `json:"dni"`
	Operacion string              `json:"operacion"`
	Resultado []string            `json:"resultado"`
	Datos     reniecDatosResponse `json:"datos"`
}

func toReniecResultResponse(r domain.ReniecResult) reniecResultResponse {
	return reniecResultResponse{
		DNI:       r.DNI,
		Operacion: r.Operacion,
		Resultado: r.Resultado,
		Datos: reniecDatosResponse{
			ApellidoPaterno: r.Datos.ApellidoPaterno,
			ApellidoMaterno: r.Datos.ApellidoMaterno,
			Nombres:         r.Datos.Nombres,
			PrimerNombre:    r.Datos.PrimerNombre,
			SegundoNombre:   r.Datos.SegundoNombre,
			TercerNombre:    r.Datos.TercerNombre,
			FechaNacimiento: r.Datos.FechaNacimiento,
			Sexo:            r.Datos.Sexo,
		},
	}
}

type sisAfiliadoResponse struct {
	IdError            string `json:"idError"`
	Resultado          string `json:"resultado"`
	TipoDocumento      string `json:"tipoDocumento"`
	NroDocumento       string `json:"nroDocumento"`
	ApePaterno         string `json:"apePaterno"`
	ApeMaterno         string `json:"apeMaterno"`
	Nombres            string `json:"nombres"`
	FecAfiliacion      string `json:"fecAfiliacion"`
	EESS               string `json:"eess"`
	DescEESS           string `json:"descEESS"`
	EESSUbigeo         string `json:"eessUbigeo"`
	DescEESSUbigeo     string `json:"descEessUbigeo"`
	Regimen            string `json:"regimen"`
	TipoSeguro         string `json:"tipoSeguro"`
	DescTipoSeguro     string `json:"descTipoSeguro"`
	Contrato           string `json:"contrato"`
	FecCaducidad       string `json:"fecCaducidad"`
	Estado             string `json:"estado"`
	Tabla              string `json:"tabla"`
	IdNumReg           string `json:"idNumReg"`
	Genero             string `json:"genero"`
	FecNacimiento      string `json:"fecNacimiento"`
	IdUbigeo           string `json:"idUbigeo"`
	Direccion          string `json:"direccion"`
	Disa               string `json:"disa"`
	TipoFormato        string `json:"tipoFormato"`
	NroContrato        string `json:"nroContrato"`
	Correlativo        string `json:"correlativo"`
	IdPlan             string `json:"idPlan"`
	IdGrupoPoblacional string `json:"idGrupoPoblacional"`
	MsgConfidencial    string `json:"msgConfidencial"`
}

func toSisAfiliadoResponse(s domain.SisAfiliado) sisAfiliadoResponse {
	return sisAfiliadoResponse{
		IdError:            s.IdError,
		Resultado:          s.Resultado,
		TipoDocumento:      s.TipoDocumento,
		NroDocumento:       s.NroDocumento,
		ApePaterno:         s.ApePaterno,
		ApeMaterno:         s.ApeMaterno,
		Nombres:            s.Nombres,
		FecAfiliacion:      s.FecAfiliacion,
		EESS:               s.EESS,
		DescEESS:           s.DescEESS,
		EESSUbigeo:         s.EESSUbigeo,
		DescEESSUbigeo:     s.DescEESSUbigeo,
		Regimen:            s.Regimen,
		TipoSeguro:         s.TipoSeguro,
		DescTipoSeguro:     s.DescTipoSeguro,
		Contrato:           s.Contrato,
		FecCaducidad:       s.FecCaducidad,
		Estado:             s.Estado,
		Tabla:              s.Tabla,
		IdNumReg:           s.IdNumReg,
		Genero:             s.Genero,
		FecNacimiento:      s.FecNacimiento,
		IdUbigeo:           s.IdUbigeo,
		Direccion:          s.Direccion,
		Disa:               s.Disa,
		TipoFormato:        s.TipoFormato,
		NroContrato:        s.NroContrato,
		Correlativo:        s.Correlativo,
		IdPlan:             s.IdPlan,
		IdGrupoPoblacional: s.IdGrupoPoblacional,
		MsgConfidencial:    s.MsgConfidencial,
	}
}

// --- CATALOG RESPONSES ---

type etniaResponse struct {
	Codigo      string  `json:"codigo"`
	Descripcion *string `json:"descripcion,omitempty"`
}

func toEtniaResponse(e domain.Etnia) etniaResponse {
	return etniaResponse{
		Codigo:      e.Codigo,
		Descripcion: e.Descripcion,
	}
}

type idiomaResponse struct {
	ID     int64   `json:"id"`
	Lengua *string `json:"lengua,omitempty"`
}

func toIdiomaResponse(i domain.Idioma) idiomaResponse {
	return idiomaResponse{
		ID:     i.ID,
		Lengua: i.Lengua,
	}
}

type catalogItemResponse struct {
	ID          int64   `json:"id"`
	Descripcion *string `json:"descripcion,omitempty"`
}

func toTipoSexoResponse(t domain.TipoSexo) catalogItemResponse {
	return catalogItemResponse{ID: t.ID, Descripcion: t.Descripcion}
}

func toTipoEstadoCivilResponse(t domain.TipoEstadoCivil) catalogItemResponse {
	return catalogItemResponse{ID: t.ID, Descripcion: t.Descripcion}
}

func toTipoGradoInstruccionResponse(t domain.TipoGradoInstruccion) catalogItemResponse {
	return catalogItemResponse{ID: t.ID, Descripcion: t.Descripcion}
}

func toTipoOcupacionResponse(t domain.TipoOcupacion) catalogItemResponse {
	return catalogItemResponse{ID: t.ID, Descripcion: t.Descripcion}
}

func toTipoDocumentoResponse(t domain.TipoDocumento) catalogItemResponse {
	return catalogItemResponse{ID: t.ID, Descripcion: t.Descripcion}
}

func toEstadoLlegoPacienteResponse(e domain.EstadoLlegoPaciente) catalogItemResponse {
	return catalogItemResponse{ID: e.ID, Descripcion: e.Descripcion}
}

type locationItemResponse struct {
	ID     int64   `json:"id"`
	Nombre *string `json:"nombre,omitempty"`
}

func toDepartamentoResponse(d domain.Departamento) locationItemResponse {
	return locationItemResponse{ID: d.ID, Nombre: d.Nombre}
}

func toProvinciaResponse(p domain.Provincia) locationItemResponse {
	return locationItemResponse{ID: p.ID, Nombre: p.Nombre}
}

func toDistritoResponse(d domain.Distrito) locationItemResponse {
	return locationItemResponse{ID: d.ID, Nombre: d.Nombre}
}

func toCentroPobladoResponse(c domain.CentroPoblado) locationItemResponse {
	return locationItemResponse{ID: c.ID, Nombre: c.Nombre}
}

func toPaisResponse(p domain.Pais) locationItemResponse {
	return locationItemResponse{ID: p.ID, Nombre: p.Nombre}
}

func toServicioResponse(s domain.Servicio) locationItemResponse {
	return locationItemResponse{ID: s.ID, Nombre: s.Nombre}
}

func toEspecialidadResponse(e domain.Especialidad) locationItemResponse {
	return locationItemResponse{ID: e.ID, Nombre: e.Nombre}
}

type fuenteFinanciamientoResponse struct {
	ID                   int64   `json:"idFuenteFinanciamiento"`
	Descripcion          *string `json:"descripcion,omitempty"`
	IdTipoFinanciamiento int64   `json:"idTipoFinanciamiento"`
}

func toFuenteFinanciamientoResponse(f domain.FuenteFinanciamiento) fuenteFinanciamientoResponse {
	return fuenteFinanciamientoResponse{
		ID:                   f.ID,
		Descripcion:          f.Descripcion,
		IdTipoFinanciamiento: f.IdTipoFinanciamiento,
	}
}

type datosInstitucionResponse struct {
	RucEESS    *string `json:"rucEess,omitempty"`
	Nombre     *string `json:"nombre,omitempty"`
	Direccion  *string `json:"direccion,omitempty"`
	Telefono   *string `json:"telefono,omitempty"`
	Codigo     *string `json:"codigo,omitempty"`
	CodRenaes  *string `json:"codRenaes,omitempty"`
	LogoHospi  *string `json:"logoHospi,omitempty"`
	LogoMinsa  *string `json:"logoMinsa,omitempty"`
	UbigeoHosp *string `json:"ubigeoHosp,omitempty"`
}

func toDatosInstitucionResponse(d domain.DatosInstitucion) datosInstitucionResponse {
	return datosInstitucionResponse{
		RucEESS:    d.RucEESS,
		Nombre:     d.Nombre,
		Direccion:  d.Direccion,
		Telefono:   d.Telefono,
		Codigo:     d.Codigo,
		CodRenaes:  d.CodRenaes,
		LogoHospi:  d.LogoHospi,
		LogoMinsa:  d.LogoMinsa,
		UbigeoHosp: d.UbigeoHosp,
	}
}
