package domain

import "time"

// PatientDetail es el modelo de lectura completo de un paciente, reflejando
// las columnas expuestas por el SP webPacientesListarIdPaciente. Es el
// equivalente Go del schema PacienteDetalle del proyecto FastAPI.
type PatientDetail struct {
	PatientID             int64      `json:"patientId"`
	DocumentNumber        *string    `json:"documentNumber,omitempty"`
	HistoryNumber         *string    `json:"historyNumber,omitempty"`
	PaternalSurname       *string    `json:"paternalSurname,omitempty"`
	MaternalSurname       *string    `json:"maternalSurname,omitempty"`
	FirstName             *string    `json:"firstName,omitempty"`
	SecondName            *string    `json:"secondName,omitempty"`
	ThirdName             *string    `json:"thirdName,omitempty"`
	DateOfBirth           *time.Time `json:"dateOfBirth,omitempty"`
	Phone                 *string    `json:"phone,omitempty"`
	HomeAddress           *string    `json:"homeAddress,omitempty"`
	AutoGenerated         *string    `json:"autoGenerated,omitempty"`
	SexTypeID             *int64     `json:"sexTypeId,omitempty"`
	OriginID              *int64     `json:"originId,omitempty"`
	EducationDegreeID     *int64     `json:"educationDegreeId,omitempty"`
	MaritalStatusID       *int64     `json:"maritalStatusId,omitempty"`
	DocIdentityID         *int64     `json:"docIdentityId,omitempty"`
	OccupationTypeID      *int64     `json:"occupationTypeId,omitempty"`
	BirthCenterID         *int64     `json:"birthCenterId,omitempty"`
	HomeCenterID          *int64     `json:"homeCenterId,omitempty"`
	FatherName            *string    `json:"fatherName,omitempty"`
	MotherName            *string    `json:"motherName,omitempty"`
	NumberingTypeID       *int64     `json:"numberingTypeId,omitempty"`
	OriginCenterID        *int64     `json:"originCenterId,omitempty"`
	Observation           *string    `json:"observation,omitempty"`
	HomeCountryID         *int64     `json:"homeCountryId,omitempty"`
	OriginCountryID       *int64     `json:"originCountryId,omitempty"`
	BirthCountryID        *int64     `json:"birthCountryId,omitempty"`
	OriginDistrictID      *int64     `json:"originDistrictId,omitempty"`
	HomeDistrictID        *int64     `json:"homeDistrictId,omitempty"`
	BirthDistrictID       *int64     `json:"birthDistrictId,omitempty"`
	FamilyRecord          *string    `json:"familyRecord,omitempty"`
	EthnicityID           *string    `json:"ethnicityId,omitempty"`
	BloodType             *string    `json:"bloodType,omitempty"`
	RhFactor              *string    `json:"rhFactor,omitempty"`
	UsesWebReniec         *bool      `json:"usesWebReniec,omitempty"`
	LanguageID            *int64     `json:"languageId,omitempty"`
	Email                 *string    `json:"email,omitempty"`
	MotherDocument        *string    `json:"motherDocument,omitempty"`
	MotherPaternalSurname *string    `json:"motherPaternalSurname,omitempty"`
	MotherMaternalSurname *string    `json:"motherMaternalSurname,omitempty"`
	MotherFirstName       *string    `json:"motherFirstName,omitempty"`
	MotherSecondName      *string    `json:"motherSecondName,omitempty"`
	ChildOrderNumber      *int64     `json:"childOrderNumber,omitempty"`
	MotherDocType         *string    `json:"motherDocType,omitempty"`
	Sector                *string    `json:"sector,omitempty"`
	Sectorist             *string    `json:"sectorist,omitempty"`
	BirthRecordNumber     *string    `json:"birthRecordNumber,omitempty"`
	EcoGenCaseNumber      *string    `json:"ecoGenCaseNumber,omitempty"`
	XRayCaseNumber        *string    `json:"xRayCaseNumber,omitempty"`
	EcogObsCaseNumber     *string    `json:"ecogObsCaseNumber,omitempty"`
	StateID               *int64     `json:"stateId,omitempty"`
	Cellphone             *string    `json:"cellphone,omitempty"`
	InsuranceTypeID       *int64     `json:"insuranceTypeId,omitempty"`
	PatientPhoto          *string    `json:"patientPhoto,omitempty"`
	PatientSignature      *string    `json:"patientSignature,omitempty"`
	DisabilityID          *int64     `json:"disabilityId,omitempty"`
	IncapacityID          *int64     `json:"incapacityId,omitempty"`
}
