package domain

import "time"

// PatientUpdate transporta los datos editables de un paciente hacia el SP
// usp_go_ModificarPaciente. Todos los campos son opcionales; un puntero nil
// se envía como NULL al procedimiento. Es el equivalente Go del schema
// PacienteUpdate del proyecto FastAPI.
type PatientUpdate struct {
	BirthCountryID    *int64     `json:"birthCountryId,omitempty"`
	MaternalSurname   *string    `json:"maternalSurname,omitempty"`
	HomeAddress       *string    `json:"homeAddress,omitempty"`
	OriginCountryID   *int64     `json:"originCountryId,omitempty"`
	PaternalSurname   *string    `json:"paternalSurname,omitempty"`
	FirstName         *string    `json:"firstName,omitempty"`
	SecondName        *string    `json:"secondName,omitempty"`
	ThirdName         *string    `json:"thirdName,omitempty"`
	DateOfBirth       *time.Time `json:"dateOfBirth,omitempty"`
	DocumentNumber    *string    `json:"documentNumber,omitempty"`
	Phone             *string    `json:"phone,omitempty"`
	Cellphone         *string    `json:"cellphone,omitempty"`
	AutoGenerated     *string    `json:"autoGenerated,omitempty"`
	SexTypeID         *int64     `json:"sexTypeId,omitempty"`
	OriginID          *int64     `json:"originId,omitempty"`
	EducationDegreeID *int64     `json:"educationDegreeId,omitempty"`
	MaritalStatusID   *int64     `json:"maritalStatusId,omitempty"`
	DocIdentityID     *int64     `json:"docIdentityId,omitempty"`
	OccupationTypeID  *int64     `json:"occupationTypeId,omitempty"`
	HomeCenterID      *int64     `json:"homeCenterId,omitempty"`
	FatherName        *string    `json:"fatherName,omitempty"`
	MotherName        *string    `json:"motherName,omitempty"`
	HomeCountryID     *int64     `json:"homeCountryId,omitempty"`
	HistoryNumber     *int64     `json:"historyNumber,omitempty"`
	BirthCenterID     *int64     `json:"birthCenterId,omitempty"`
	OriginCenterID    *int64     `json:"originCenterId,omitempty"`
	OriginDistrictID  *int64     `json:"originDistrictId,omitempty"`
	HomeDistrictID    *int64     `json:"homeDistrictId,omitempty"`
	BirthDistrictID   *int64     `json:"birthDistrictId,omitempty"`
	EthnicityID       *string    `json:"ethnicityId,omitempty"`
	LanguageID        *int64     `json:"languageId,omitempty"`
	Email             *string    `json:"email,omitempty"`
	DisabilityID      *int64     `json:"disabilityId,omitempty"`
	IncapacityID      *int64     `json:"incapacityId,omitempty"`
	AuditUserID       *int64     `json:"auditUserId,omitempty"`
}
