package domain

import "time"

// PatientDetail es el modelo de lectura completo de un paciente, reflejando
// las columnas expuestas por el SP webPacientesListarIdPaciente. Es el
// equivalente Go del schema PacienteDetalle del proyecto FastAPI.
type PatientDetail struct {
	PatientID             int64
	DocumentNumber        *string
	HistoryNumber         *string
	PaternalSurname       *string
	MaternalSurname       *string
	FirstName             *string
	SecondName            *string
	ThirdName             *string
	DateOfBirth           *time.Time
	Phone                 *string
	HomeAddress           *string
	AutoGenerated         *string
	SexTypeID             *int64
	OriginID              *int64
	EducationDegreeID     *int64
	MaritalStatusID       *int64
	DocIdentityID         *int64
	OccupationTypeID      *int64
	BirthCenterID         *int64
	HomeCenterID          *int64
	FatherName            *string
	MotherName            *string
	NumberingTypeID       *int64
	OriginCenterID        *int64
	Observation           *string
	HomeCountryID         *int64
	OriginCountryID       *int64
	BirthCountryID        *int64
	OriginDistrictID      *int64
	HomeDistrictID        *int64
	BirthDistrictID       *int64
	FamilyRecord          *string
	EthnicityID           *string
	BloodType             *string
	RhFactor              *string
	UsesWebReniec         *bool
	LanguageID            *int64
	Email                 *string
	MotherDocument        *string
	MotherPaternalSurname *string
	MotherMaternalSurname *string
	MotherFirstName       *string
	MotherSecondName      *string
	ChildOrderNumber      *int64
	MotherDocType         *string
	Sector                *string
	Sectorist             *string
	BirthRecordNumber     *string
	EcoGenCaseNumber      *string
	XRayCaseNumber        *string
	EcogObsCaseNumber     *string
	StateID               *int64
	Cellphone             *string
	InsuranceTypeID       *int64
	PatientPhoto          *string
	PatientSignature      *string
	DisabilityID          *int64
	IncapacityID          *int64
}
